resources:
  - name: distroless_base_image
    type: GitRepo
    configuration:
      gitProvider: shahin_test
      path: shahiinn/jfrog-distroless
      branches:
        include: ^{{gitBranch}}$
  - name: file_start
    type: FileSpec
    configuration:     
      sourceArtifactory: artifact_test
      pattern: testrepo1/distro-build.sh
      target: distro-build.sh        
  - name: charttestingArtifactory
    type: BuildInfo
    configuration:
      sourceArtifactory: artifact_test
      buildName: Distroless_base_image_build
      buildNumber: ${run_number}
pipelines:
  - name: Distroless_base_image_build
    steps:    
      - name: Start
        type: Bash
        configuration:
          inputResources:
            - name: file_start
          outputResources:
            - name: distroless_base_image
        execution:
          onExecute:
            - echo "Starting the build"
          onSuccess:
            - echo "Triggered the build"
      - name: Bazel_build_artifactory
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: insready/bazel
                tag: latest
          affinityGroup: image1
          inputSteps:
            - name: Start
          inputResources:
            - name: distroless_base_image
          outputResources:
            - name: charttestingArtifactory
          integrations:
            - name: artifact_test
        execution:
          onExecute:
            - echo "Starting the build"
            - pushd $res_distrolessGithubRepo_resourcePath
            - bazel build base/artifactory-sh
