resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: shahin_git                       # <- Change to your integration name
      path: shahiinn/project-examples   # <- Change to your forked repo
      branches:
        include: master
 
pipelines: 
  - name: basic_pipeline
    configuration:
      environmentVariables:
        readOnly:
          my_env_var: "hello" 
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myGitRepo
          outputResources:
            - name: myBuildInfo            
        execution:
          onExecute:
            - echo $my_env_var
            - if [ -z $app_version ]; then add_pipeline_variables app_version=1.0.0; else app_version=$(bump_semver $app_version minor); fi
            - write_output myBuildInfo "buildNumber=$app_version"
            - add_run_variables run_var="hello"
 
  - name: artifactory_installer_oss_build
    type: MvnBuild
    configuration:
      sourceLocation: maven-example
      mvnCommand: install 
      inputSteps:
        - name: step_1
      inputResources:
        - name: myGitRepo
          trigger: true
